# Generated by Django 5.2.7 on 2025-10-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PainelSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('potencia', models.CharField(max_length=50)),
                ('dataFabr', models.DateField(verbose_name='Data de Fabricação')),
                ('dataInst', models.DateField(verbose_name='Data de Instalação')),
                ('qtdCel', models.PositiveIntegerField(verbose_name='Quantidade de Células')),
                ('tipo', models.CharField(choices=[('Monocristalino', 'Monocristalino'), ('Policristalino', 'Policristalino'), ('Híbrido', 'Híbrido'), ('Filme Fino', 'Filme Fino (a-Si, CdTe, CIGS)')], max_length=30)),
                ('estado', models.CharField(choices=[('Funciona', 'Funciona'), ('Parcialmente', 'Funciona parcialmente'), ('Não funciona', 'Não funciona')], max_length=30)),
                ('condicao', models.CharField(choices=[('Inteiro', 'Inteiro'), ('Trincado', 'Trincado'), ('Quebrado', 'Quebrado')], max_length=30)),
                ('motivo', models.CharField(choices=[('Quebra', 'Quebra'), ('Fim da Vida Útil', 'Fim da vida útil'), ('Troca', 'Troca'), ('Desinstalação', 'Desinstalação')], max_length=50)),
                ('inversor', models.CharField(choices=[('On-Grid', 'On-Grid'), ('Off-Grid', 'Off-Grid'), ('String', 'String'), ('Híbrido', 'Híbrido'), ('Microinversor', 'Microinversor'), ('Central', 'Central')], max_length=30)),
                ('comentarios', models.TextField()),
                ('tensao', models.CharField(max_length=50)),
                ('corrente', models.CharField(max_length=50)),
                ('eficiencia', models.CharField(max_length=50)),
                # ('dimensao', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=50)),
                ('dataColeta', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
