# Generated by Django 5.2.7 on 2025-10-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolar', '0003_alter_userprofile_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nome',
            field=models.CharField(default='semnome', max_length=150),
            preserve_default=False,
        ),
    ]
