# Generated by Django 5.2.7 on 2025-10-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolar', '0004_userprofile_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creditos',
            field=models.FloatField(default=0),
        ),
    ]
