# Generated by Django 5.2.7 on 2025-10-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolar', '0005_userprofile_creditos'),
    ]

    operations = [
        migrations.AddField(
            model_name='painelsolar',
            name='dono',
            field=models.CharField(default='sem-dono', max_length=100),
            preserve_default=False,
        ),
    ]
