# Generated by Django 5.2.7 on 2025-10-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolar', '0009_alter_painelsolar_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painelsolar',
            name='dono',
            field=models.CharField(max_length=100),
        ),
    ]
