# Generated by Django 5.2.7 on 2025-10-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolar', '0011_alter_painelsolar_dono'),
    ]

    operations = [
        migrations.AddField(
            model_name='painelsolar',
            name='creditos',
            field=models.FloatField(default=0),
        ),
    ]
